server:
  port: 8001

spring:
  application:
    name : config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oksw2024/spring-cloud-pj-config
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true